# config.yaml
# === Subject info ===
subinfo_fields:
  - name: subject_id
    type: int
    constraints:
      min: 101
      max: 999
      digits: 3

  - name: subname    
    type: string

  - name: age 
    type: int
    constraints:
      min: 5
      max: 60

  - name: gender
    type: choice
    choices: [Male, Female]

subinfo_mapping:
    subject_id: "被试号"
    subname: "被试姓名(拼音)"
    age: "年龄"
    gender: "性别"
    Male: "男"
    Female: "女"
    registration_failed: "注册失败。"
    registration_successful: "注册成功！"
    invalid_input: "字段 {field} 输入无效"


# === Window settings ===
window:
  size: [1920, 1080]
  units: deg
  screen: 1
  bg_color: gray
  fullscreen: True
  monitor_width_cm: 60
  monitor_distance_cm: 72

# === Task-level settings ===
task:
  task_name: "eeg_sst"
  save_path: ./outputs/qa
  language: "Chinese"
  voice_name: "zh-CN-YunyangNeural"
  total_blocks: 1
  total_trials: 24
  trial_per_block: 24
  conditions: [go_left, go_right, stop_left, stop_right]
  key_list: [f, j]
  left_key: f
  right_key: j
  delta: 0.05
  voice_enabled: false
  seed_mode: "same_across_sub"


# === Stimuli (for SST task) ===
stimuli:
  fixation:
    type: text
    text: "+"
    color: white
  go_left:
    type: shape
    vertices:
      - [ 0.20,  0.05]
      - [ 0.20, -0.05]
      - [ 0.00, -0.05]
      - [ 0.00, -0.10]
      - [-0.20,  0.00]
      - [ 0.00,  0.10]
      - [ 0.00,  0.05]
    fillColor: white
    size: 8
    lineColor: ''

  go_right:
    type: shape
    vertices:
      - [-0.20,  0.05]
      - [-0.20, -0.05]
      - [ 0.00, -0.05]
      - [ 0.00, -0.10]
      - [ 0.20,  0.00]
      - [ 0.00,  0.10]
      - [ 0.00,  0.05]
    fillColor: white
    size: 8
    lineColor: ''

  stop_signal:
    type: sound
    file: .\assets\beep.mp3

  no_response_feedback  :
    type: text
    text: |
      【未按键】
      请在箭头出现后按键
    font: SimHei
    height: 0.78



  block_break:
    type: text
    text: |
      【休息提示】

      第 {block_num} / {total_blocks} 部分完成。
      击中率：{go_accuracy:.2f}
      正确停止率：{stop_accuracy:.2f}

      请在充分休息后按【空格键】
      进入下一部分
    color: white
    font: SimHei
    height: 0.78


  instruction_text:
    type: textbox
    text: |
      【停止信号任务说明】

      在本任务中，您将看到箭头指向左或右
      您的目标是尽快且准确地做出反应
        - 如果箭头指向左，请用左手食指按【F】
        - 如果箭头指向右，请用右手食指按【J】

      注意：在某些试次中
      当听到【哔】声时
      请尽力抑制您的反应不要按任何按键

      在没有【哔】声出现时，请快速做出反应
      出现【哔】声时，请尽量不做出任何按键反应

      准备好后，请按【空格键】开始任务。
    color: white
    font: SimHei
    alignment: center
    letterHeight: 0.78
    units: deg
    size: [20, 5]


  good_bye:
    type: textbox
    text: |
      任务结束
      
      感谢您的参与
      请按【空格键】键退出
    color: white
    font: SimHei
    alignment: center
    letterHeight: 0.78

# === Timing & Adaptivity ===
timing:
  fixation_duration: [0.8, 1]
  go_duration: 1.0        
  no_response_feedback_duration: 0.8

# === Triggers ===
triggers:
  map:
    exp_onset: 98
    exp_end: 99

    block_onset: 100
    block_end: 101

    fixation_onset: 1
    go_onset: 10
    go_response: 11
    go_miss: 12
    pre_stop_onset: 22
    pre_stop_response: 23
    on_stop_onset: 24
    on_stop_response: 25
    post_stop_response: 26
    no_response_feedback_onset: 30

  driver:
    type: serial_url
    url: loop://
    baudrate: 115200
    timeout: 1
    prefix: [1, 225, 1, 0]

  policy:
    strict: false

  timing:
    post_delay_s: 0.001


# === Controller ===
controller:
  initial_ssd: 0.25             # initial stop‐signal delay (in seconds)
  step: 0.05            # staircase step size (in whatever units you define)
  min_ssd: 0.05
  max_ssd: 0.5
  target_success: 0.5  # 1-up 1-down

qa:
  output_dir: outputs/qa
  enable_scaling: true
  timing_scale: 0.05
  min_frames: 1
  strict: false
  max_wait_s: 10.0
  acceptance_criteria:
    required_columns:
      - condition
    expected_trial_count: 24
    allowed_keys: [f, j]
    triggers_required: true
